### ISSUE TITLE
Apple banned my real MacBook Pro from using iMessage after running this tool for a couple of days

### ISSUE THREAD

**Issue by pricead** [beeper/mac-registration-provider#13]
Be aware, Apple has been banning Macs that share their credentials for Beeper. 

After running this tool for a few days to use with my Android phone with Beeper Mini, I can no longer send iMessages from my Mac to any of my friends with iPhones. The sent messages instantly fail. There are some posts on Reddit confirming a similar problem. I've tried logging out of iCloud on my Mac and logging back in, and the problem still occurs. I have yet to try calling Apple Support because I'm not sure how helpful they would be to someone my situation.

I highly advise not running this tool if you care about using your computer with iMessage.

**Comment by war59312** [comment]
I was wondering if banned here too.

Now getting when running this tool:

`Error in relay connection: failed to read request: failed to read JSON message: failed to get reader: failed to read frame header: EOF, reconnecting in ...`

Get the same registration code printed on the screen, but back in Bepper; trying to send a msg results in `requested user is not on iMessage`

**Comment by jetfir3** [comment]
As of 2 days ago, my Mac has had the "Apple-side" block. Was used to register Beeper Mini. It lasted less than 48hrs before I first noticed I couldn't send new messages within Beeper Mini. Then confirmed on physical Mac. I had only sent a single message through Beeper Mini as a test... then received a single message back. 

I imagine I'd have to call Apple Support to try and rectify this -- the support chat only seems available on iOS/iPadOS. Those who have gotten theirs fixed also mentioned the Apple representative saying it would be a "one-time" thing. Will let the dust settle and see if any new info is learned over the next few weeks before making a move. 

At the moment I can still run the `mac-registration-provider` binary to generate a registration code and register/sign-in to Beeper Mini but unable to see any previous chats or send/receive any messages.

**Comment by 0xdevalias** [comment]
Just saw a post on Reddit mentioning similar:

- https://www.reddit.com/r/beeper/comments/18ztlac/apple_email_about_macbook_being_restricted_from/

**Comment by pricead** [comment]
Checked again today and my Mac seems unbanned now. I never talked to Apple support. 

I've been checking every few days and it's possible that it's been 30 days today since my ban was issued and that was the expiration of the ban, or someone at Apple realized that this was a very bad way to treat customers.

I won't be running any Beeper software on my Mac in the future.

**Comment by jetfir3** [comment]
Can confirm my ban has also been lifted and Messages app is working again.

**Comment by war59312** [comment]
I'm not willing to risk it, so I switched over to BlueBubbles, and it has been working great, from day 1, about a week ago.
