### ISSUE TITLE
macOS Ventura Error: No offsets found for 13.6.1/22G313/amd64

### ISSUE THREAD

**Issue by smizles** [beeper/mac-registration-provider#17]
I followed the documentation and ran the utility in Terminal. See the results and error below.

```
user@MBP2017 Downloads % ./mac-registration-provider
2024/01/03 17:37:53 Starting mac-registration-provider 5789044a
2024/01/03 17:37:53 Loading identityservicesd
2024/01/03 17:37:53 No offsets found for 13.6.1/22G313/amd64 (hash: fff8db27fef2a2b874f7bc6fb303a98e3e3b8aceb8dd4c5bfa2bad7b76ea438a)
```

**Comment by 0xdevalias** [comment]
@jetfir3 If you felt like reversing some more versions.

---

> Curious, how do you have access to the older binaries? Extracting them from Time Machine backups/similar, or?
> 
> _Originally posted by @0xdevalias in https://github.com/beeper/mac-registration-provider/pull/12#discussion_r1440069330_

> Downloading macOS and extracting the binary for each version. 
> 
> https://github.com/corpnewt/gibMacOS
> https://support.apple.com/kb/DL2052
> etc
> 
> _Originally posted by @jetfir3 in https://github.com/beeper/mac-registration-provider/pull/12#discussion_r1440476750_

**Comment by jetfir3** [comment]
@0xdevalias -- based on the "error" output in the OP, the hash of the 13.6.1`identityservicesd` binary (fff8db27fef2a2b874f7bc6fb303a98e3e3b8aceb8dd4c5bfa2bad7b76ea438a) matches the current hash of the already-supported 13.6 (https://github.com/beeper/mac-registration-provider/blob/main/nac/offsets.go#L135) -- which was added by your own PR.

So the error seems to not add up -- am I missing something?

**Comment by 0xdevalias** [comment]
Oh true.. I didn't even notice that 😅

Maybe this was before I added that version/not compiled from code that includes it.

**Comment by tulir** [comment]
> 2024/01/03 17:37:53 Starting mac-registration-provider 5789044a

That is indeed an old version
