### ISSUE TITLE
No offsets found for 14.3 Beta 3

### ISSUE THREAD

**Issue by dseehof** [beeper/mac-registration-provider#22]
I see a commit for the latest beta, but am getting no offset found.

**Comment by tulir** [comment]
Are you running the commit for the latest beta?

**Comment by jmcwheeler** [comment]
Same for me with the latest beta. Mac OS Version 14.3 Beta (23D5051b)

**Comment by skiman6010** [comment]
Are you running the latest build artifact from the last commit?

**Comment by jmcwheeler** [comment]
> Are you running the latest build artifact from the last commit?
> 
> https://nightly.link/beeper/mac-registration-provider/workflows/go/main/mac-registration-provider-universal.zip

Worked for me with that version. Although even with my new code I'm still not able to send/recieve iMessages through the bridge.
