### ISSUE TITLE
This does not support updated Intel Macs

### ISSUE THREAD

**Issue by joshuajohncohen** [beeper/mac-registration-provider#23]
Intel Macs only support Monterey, so to work on most updated Intel Macs this tool would need to support the latest versions of Monterey.

**Comment by 0xdevalias** [comment]
That's not true..? My Intel Mac is currently on Ventura, and I can upgrade it to Sonoma as well.

**Comment by jetfir3** [comment]
Ventura seems to have cut off support for 2017 and earlier devices (perhaps there are some exceptions). Any Intel device newer than that could certainly update beyond 12.x. 

12.7.2 is the current latest Monterey build -- feel free to upload the `/System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd` binary somewhere so the offsets can be added. 

This situation has pretty much been covered in previously submitted Issues. If a macOS version isn't supported, add the offsets via PR or share the binary so someone else can.

**Comment by 0xdevalias** [comment]
> This situation has pretty much been covered in previously submitted Issues. If a macOS version isn't supported, add the offsets via PR or share the binary so someone else can. 

I wonder if an update to the README or issue templates or similar might help guide people towards doing that better?

**Comment by jetfir3** [comment]
> I wonder if an update to the README or issue templates or similar might help guide people towards doing that better?

Certainly something worth considering. Some initial thoughts are: 
- if they aren't reading open and closed issues -- where will they read? Perhaps BOTH the README and an issues template would cover those bases... but either would be better than nothing, for sure. A Discussion post or FAQ/Wiki entry would be easier to ignore/miss and probably not be as effective. 
- but if additional text is added somewhere -- what is the best protocol for sharing a binary? Should it always be uploaded to an external source and not attached directly in github to avoid potential legal issues? Does "officially" asking people to share binaries open up any legal issues? 

I'm probably overthinking it :)

**Comment by joshuajohncohen** [comment]
I made a PR in #25

**Comment by 0xdevalias** [comment]
> Here is the binary for 12.7.2:

```bash
⇒ sha256sum macos-12.7.2-monterey-identityservicesd
01aaa511c5d32c5766256a40b5ae8f42fb49b74074dce5936f315244236f15a0  macos-12.7.2-monterey-identityservicesd
```

**Comment by jetfir3** [comment]
Added a PR for 12.7.2 support - https://github.com/beeper/mac-registration-provider/pull/29

Didn't realize until after disassembling that the offsets match the already-existing 12.7.1 offsets, just needed to update the binary hash.  :|
