### ISSUE TITLE
Offset not found

### ISSUE THREAD

**Issue by MR-UNI** [beeper/mac-registration-provider#24]
When attempting to run this application on MacOS Sonoma 14.3 23D5051b , i get the following error

2024/01/15 21:38:19 Starting mac-registration-provider 796b7e34
2024/01/15 21:38:19 Loading identityservicesd
2024/01/15 21:38:19 No offsets found for 14.3/23D5051b/arm64 (hash: 925c30618e05ee9e8f457073c8adb4e72f67b974a27855f7d463d69018d97822)

I am currently using an M2 Mini base model.

**Comment by MR-UNI** [comment]
Mac system report : 
 Model Name:	Mac mini
  Model Identifier:	Mac14,3
  Model Number:	MMFK3LL/A
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	10151.81.1
  OS Loader Version:	10151.81.1
  Serial Number (system):	(REDACTED)
  Hardware UUID:	(REDACTED)
  Provisioning UDID:	(REDACTED)
  Activation Lock Status:	Enabled

**Comment by 0xdevalias** [comment]
It looks like there are only currently offsets for 14.3 betas:

- https://github.com/beeper/mac-registration-provider/blob/main/nac/offsets.go

Is the version you're on the final release? (I'm not on Sonoma yet so haven't been paying close attention)

**Comment by tulir** [comment]
All versions are compiled in github actions, there's a direct link to the latest build in the readme

**Comment by MR-UNI** [comment]
> All versions are compiled in github actions, there's a direct link to the latest build in the readme

thank you, I found the action. this happens too often with different apps so I decided to just turn off beta enrollment

**Comment by MR-UNI** [comment]
> It looks like there are only currently offsets for 14.3 betas:
> 
> - https://github.com/beeper/mac-registration-provider/blob/main/nac/offsets.go
> 
> ~~Is the version you're on the final release? (I'm not on Sonoma yet so haven't been paying close attention)~~
> 
> Looks like that should be 14.3 beta 3 I think:
> 
> - https://betawiki.net/wiki/MacOS_Sonoma_build_23D5051b
> 
> Which is supported. So make sure you're running the latest version of the code (and if a compiled version hasn't been released that includes that change yet, you may have to build it from source)

> I found the action for the precomposed version, thank you for your help 🙂
