### ISSUE TITLE
identityservicesd 14.3 (23D56)

### ISSUE THREAD

**Issue by cameronaaron** [beeper/mac-registration-provider#27]
We need to add compatibility with 14.3 (23D56)

identityservicesd 14.3 (23D56)
[identityservicesd.zip](https://github.com/beeper/mac-registration-provider/files/13999454/identityservicesd.zip)

**Comment by 0xdevalias** [comment]
Is this one of the various beta versions (alongside the ones already supported); or is this a 'final release' version now?

**Comment by cameronaaron** [comment]
final

**Comment by jetfir3** [comment]
Most likely the Release Candidate which was released ~4 days ago.
This binary may or may not match what actually makes it to the final/stable 14.3 release.

**Comment by 0xdevalias** [comment]
```bash
⇒ sha256sum macos-14.3-23D56-sonoma-identityservicesd
d3c6986fefcbd2efea2a8a7c88104bf22d60d1f4f2bbf3615a1e3ce098aba765  macos-14.3-23D56-sonoma-identityservicesd
```
