### ISSUE TITLE
newer version of mac

### ISSUE THREAD

**Issue by dsdavidoff** [beeper/mac-registration-provider#30]
Following instructions here to create an issue and upload the relevant file: https://github.com/beeper/mac-registration-provider/pull/25/files
[identityservicesd.zip](https://github.com/beeper/mac-registration-provider/files/14185777/identityservicesd.zip)

Running Sonoma 14.3 on Intel Core i7
<img width="468" alt="Screenshot 2024-02-06 at 3 36 48 PM" src="https://github.com/beeper/mac-registration-provider/assets/47550694/05ab0e2f-5bd2-44c3-bba2-e19fa9c2850d">

Error messages when I follow the readme:
(base) dani@Dani-Davidoffs-MacBook-Pro downloads % ./mac-registration-provider
2024/02/06 15:21:19 Starting mac-registration-provider 796b7e34
2024/02/06 15:21:19 Loading identityservicesd
2024/02/06 15:21:19 No offsets found for 14.3/23D56/amd64 (hash: d3c6986fefcbd2efea2a8a7c88104bf22d60d1f4f2bbf3615a1e3ce098aba765)

**Comment by tulir** [comment]
That's an outdated version of the provider

**Comment by 0xdevalias** [comment]
By which they mean: "that version is already supported if you update to the latest version"
