### ISSUE TITLE
Incorrectly detects arm64 on x86_64?

### ISSUE THREAD

**Issue by cvincent** [beeper/mac-registration-provider#46]
On a Mac Mini Intel Core i5 running Mojave 10.14.6:

```
No offsets found for 10.14.6/18G103/amd64
```

But `uname -m` reports `x86_64`. Looking at the source, it seems like `runtime.GOARCH` is incorrect somehow? I've never developed in Go, and this Mac Mini is solely so I can get iMessage back into Beeper, so it's not exactly set up for development or I'd try hacking a fix myself. :P

**Comment by tulir** [comment]
amd64 = x86_64

Some macOS versions can have different identityservicesd binaries (e.g. depending on hardware), which would cause it to not find offsets even though other builds of the same version are supported. The supported hashes can be found at https://github.com/beeper/mac-registration-provider/blob/main/nac/offsets.go#L204-L253 and you can find your own hash using `sha256sum /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd`

**Comment by cvincent** [comment]
In that case it seems the support matrix in the README can sometimes be misleading; as this is an Intel Mac, and the README lists "10.14.6" under Intel as being supported. How can I determine what version of macOS I can install on this machine that *is* supported? I'll happily install that instead.
