### ISSUE TITLE
macOS 13.6.4 throws "Incompatible macOS Version" despite README listing it as compatible

### ISSUE THREAD

**Issue by gabefletch** [beeper/mac-registration-provider#49]
<img width="1096" alt="Screenshot 2024-05-31 at 2 44 34 PM" src="https://github.com/beeper/mac-registration-provider/assets/38300939/5fa32a56-3fe1-499f-b435-9dcd82f104e1">

**Comment by tulir** [comment]
The readme describes the state of this repository specifically, it's not meant for documenting what's in beeper desktop
